language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

gemfile:
  - test/gemfiles/Gemfile.rails-3.0.x
  - test/gemfiles/Gemfile.rails-3.1.x
  - test/gemfiles/Gemfile.rails-3.2.x

matrix:
  include:
    - rvm: 2.0.0
      gemfile: test/gemfiles/Gemfile.rails-3.2.x

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
